name: CI/CD for Tomcat with Docker

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  # Use the Java version your project requires

      - name: Change Permissions for Java Files
        run: |
          # Change permissions for all Java files
          chmod +x ./apache-tomcat-10.1.28/webapps/trivia/WEB-INF/classes/*.java
          chmod +x ./apache-tomcat-10.1.28/lib/*

      - name: Compile Java Files
        run: |
          # Change to the directory containing your Java source files
          cd ./apache-tomcat-10.1.28/webapps/trivia/WEB-INF/classes
          
          # Print the current working directory to verify
          pwd
          
          # List all files in the directory to ensure Java files are present
          ls -al
          
          # Construct the classpath
          CLASSPATH=.:../../../../lib/*
          
          # Compile the Java files
          javac -cp "$CLASSPATH" *.java

      - name: Create Logs Directory
        run: |
          mkdir -p ./apache-tomcat-10.1.28/logs  # Create the logs directory if it doesn't exist


      - name: Start Tomcat Server
        run: |
          cd ./apache-tomcat-10.1.28/bin  # Use relative path to the Tomcat bin folder
          chmod +x startup.sh  # Make sure the startup script is executable
          chmod +x catalina.sh  # Ensure catalina.sh is executable
          set -x  # Enable debugging
          ./catalina.sh start  # Start Tomcat
