name: CI/CD for Tomcat with Docker

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'  # Use the Java version your project requires

      - name: Compile Java Files
        run: |
          # Change to the directory containing your Java source files
          cd ./apache-tomcat-10.1.28/webapps/trivia/WEB-INF/classes
          
          # Print the current working directory to verify
          pwd
          
          # List all files in the directory to ensure Java files are present
          ls -al
          
          # Construct the classpath
          CLASSPATH=./apache-tomcat-10.1.28/lib/BCrypt.jar;./apache-tomcat-10.1.28/lib/ojdbc8.jar;./apache-tomcat-10.1.28/lib/servlet-api.jar;./apache-tomcat-10.1.28/lib/gson-2.10.1.jar
          
          # Compile the Java files
          javac -cp "$CLASSPATH" *.java


      - name: Start Tomcat Server
        run: |
          cd ./apache-tomcat-10.1.28/bin  # Use relative path to the Tomcat bin folder
          ./startup.bat  # Start Tomcat on Linux/Mac
          # For Windows, you would use startup.bat
